---
version: "3.7"

services:
  certbot:
    image: ghcr.io/face0b1101/certbot-cloudflare
    restart: unless-stopped
    container_name: certbot
    volumes:
      - certificates:/etc/letsencrypt
      - ${DOCKER_HOME}/certbot-docker-autorenew/scripts/:/scripts/
      - ${DOCKER_HOME}/certbot-docker-autorenew/logs:/var/log/letsencrypt
    environment: 
      - DAYS=1
      - EMAIL=${CF_EMAIL}
      - CERTNAME=${CERTNAME}
      - DOMAINS=${CF_DOMAINS}
      - CREATE_NEW_CERT=false
      - CLOUDFLARE_API_TOKEN=/run/secrets/dns_cloudflare_api_token.ini
    secrets:
      - dns_cloudflare_api_token.ini
    networks:
      - my_network

volumes:
  certificates:
    name: certificates
    external: true

networks:
  my_network:
    name: my_network

secrets:
  dns_cloudflare_api_token.ini:
    file: ${DOCKER_HOME}/certbot-docker-autorenew/.secrets/dns_cloudflare_api_token.ini
