---
version: "3.7"

services:
  certbot:
    image: ghcr.io/face0b1101/certbot-cloudflare
    restart: unless-stopped
    container_name: certbot
    volumes:
      - certificates:/etc/letsencrypt
      - ${DOCKER_HOME}/certbot/scripts/:/scripts/
      # - ${DOCKER_HOME}/certbot/letsencrypt/lib:/var/lib/letsencrypt
    environment: 
      - EVERY_DAYS=1
      - EMAIL=${CF_EMAIL}
      - DOMAINS=${CF_DOMAINS}
      - RENEW_IF_VALID=no
      - CLOUDFLARE_API_TOKEN=/run/secrets/cloudflare_api_key
    secrets:
      - cloudflare_api_key

volumes:
  certificates:
    name: certificates
    external: true

secrets:
  cloudflare_api_key:
    file: ${DOCKER_HOME}/certbot-docker-autorenew/secrets/cloudflare_api_key
