---
version: "3.7"

services:
  certbot:
    image: ghcr.io/face0b1101/certbot-cloudflare
    restart: unless-stopped
    container_name: certbot
    volumes:
      - certificates:/etc/letsencrypt
      - ${DOCKER_HOME}/certbot-docker-autorenew/scripts/:/scripts/
      - ${DOCKER_HOME}/certbot-docker-autorenew/logs:/var/log/letsencrypt
      # - ${DOCKER_HOME}/certbot/letsencrypt/lib:/var/lib/letsencrypt
    environment: 
      - DAYS=1
      - EMAIL=${CF_EMAIL}
      - DOMAINS=${CF_DOMAINS}
      - RENEW_IF_VALID=true
      - CLOUDFLARE_API_TOKEN=/run/secrets/dns_cloudflare_api_token.ini
    secrets:
      - dns_cloudflare_api_token.ini

volumes:
  certificates:
    name: certificates
    external: true

secrets:
  dns_cloudflare_api_token.ini:
    file: ${DOCKER_HOME}/certbot-docker-autorenew/.secrets/dns_cloudflare_api_token.ini
